### ISSUE TITLE
A 1.0: Brak zmiany sposobu poruszania się gracza

### ISSUE THREAD

**Issue by Ucheesename** [CiupagaPL/TEBowy_Dzien#11]
Po wyłączeniu opisu nauczycieli zaczynając walkię z bossem postać otrzymuje chmurkę ale nie umie latać i porusza się jak zwykle.

**Comment by ciupagacz** [comment]
Zamiast tylko tutorialu wyłączały się zmiennie gracza, naprawione w nowym patchu
