### ISSUE TITLE
A 1.0: Zbugowany poradnik i przejście

### ISSUE THREAD

**Issue by Ucheesename** [CiupagaPL/TEBowy_Dzien#12]
Po kliknięciu enter na początku gry przełączyłem się na fullscreen przez f11. Po wyłączeniu poradnika w ustawieniach mimo wszystko jednorazowo pojawia się na początku gry. Podczas gry włączyłem poradnik i zresetowałem poziom co doprowadziło do takiego czarnego ekranu. 

![Zrzut ekranu 2024-11-27 003217](https://github.com/user-attachments/assets/e8fa5098-793c-48a3-b190-1ccb48478a0b)

Po odświeżeniu strony kliknąłem f11 od razu przed kliknięciem enter. Tym razem po wyłączeniu poradników w menu i wejściu do poziomu poradnik pojawił się po kliknięciu esc. Po anulowaniu tym samym klawiszem i kliknięciu esc jeszcze raz miałem normalne menu (takie normalne podczas gry) gdzie mogłem znowu włączyć poradniki by jeszcze raz zresetować poziom i zrobić sobie taki czarny ekran. Po ponownym kliknięciu f11 wraca się do menu ale próba gry przez Start lub wybranie poziomu kończy się tym samym czarnym ekranem. Podczas takiego czarnego ekranu można sobie spamić skakaniem (każde kliknięcie słychać jakby postać skoczyła przez co można spamić dźwiękiem)

**Comment by ciupagacz** [comment]
Wszystko powinno już działać :-)
