### ISSUE TITLE
A 1.0: Nie załadowywujący się skin postaci

### ISSUE THREAD

**Issue by CiupagaPL** [CiupagaPL/TEBowy_Dzien#13]
Tekst obecnej strony w selektorze postaci zmienia swój rozmiar w trakcie. Przy wybraniu postaci 4 w grze występuje krytyczny błąd

**Comment by ciupagacz** [comment]
Zepsuła się w poprzednim patchu funkcja renderująca skin 4, rozmiar był aktualizowany przy kliknięciu któregoś z przycisków, oczywiście wszystko naprawiłem :-)
