### ISSUE TITLE
A 1.0: Błąd podczas przejścia z ostatniej sceny do menu

### ISSUE THREAD

**Issue by Ucheesename** [CiupagaPL/TEBowy_Dzien#15]
klikam enter, wchodzę w poziomy i wybieram dziesiąty, przechodzę bossa i po powrocie do lobby ono jakby ciągle się odświeża i miga na czarno.

PS. większość błędów naprawione :tada: teraz trudniej mi znaleźć nowe

**Comment by ciupagacz** [comment]
naprawiłem z rozszerzeniem ostatniego poziomu
