### ISSUE TITLE
A 1.0: Zła pozycja znaku

### ISSUE THREAD

**Issue by Ucheesename** [CiupagaPL/TEBowy_Dzien#2]
![Zrzut ekranu 2024-11-25 215058](https://github.com/user-attachments/assets/2627f1e4-6f90-4a7d-ab05-c528dcd1ae7d)

normalnie znak jest na swoim miejscu ale po kliknięciu f11 i zresetowaniu gry on już tak zostaje. Kamera też leci wyżej niż zwykle (musiałem podskoczyć żeby kamera pokazała znak).

**Comment by ciupagacz** [comment]
Od teraz zamiast _platform.besty jest stosowany system matematyczny, działa też na różnych długościach poziomów
