### ISSUE TITLE
A 1.1: Automatyczna zmiana skina w niektórych scenach

### ISSUE THREAD

**Issue by CiupagaPL** [CiupagaPL/TEBowy_Dzien#22]
Z jakiegoś powodu nie wybierając wcześniej postaci wkraczając na poziom 10 (i zapewne nie tylko) automatycznie zastosowywuje się skin 2 zamiast 1 :-P

**Comment by ciupagacz** [comment]
Okazuje się że to samo dzieje się z drugą postacią z okryciem głowy <3

**Comment by ciupagacz** [comment]
Najprawdopodbniej powodem jest #25

**Comment by ciupagacz** [comment]
Był to jeden z najdziwniejszych bugów które naprawiałem od dawna, faktycznie było powiązane z #25.
