### ISSUE TITLE
A 1.0: Wyjście poza mapę

### ISSUE THREAD

**Issue by Ucheesename** [CiupagaPL/TEBowy_Dzien#3]
![Zrzut ekranu 2024-11-25 215144](https://github.com/user-attachments/assets/4266e103-284b-4193-bc85-897a9adb3616)
![Zrzut ekranu 2024-11-25 215156](https://github.com/user-attachments/assets/ac7a03dd-8835-4121-8d9c-42c76f127ad3)

Kiedy walczy się z bossem to można dotknąć podłogi co lekko klinuje w niej postać. Można albo się z niej wydostać (klikając kilka razy klawisz w górę co sprawia że postać lekko przeskakuje na górę dopóki się nie wydostanie) albo wejść pod mapę klikając kilka razy klawisz w dół. Pod podłogą postać też porusza się swobodnie i można schodzić na dół (chyba) w nieskończoność. Można tą samą metodą wrócić na mapę.

**Comment by ciupagacz** [comment]
Jest to najprawdopodobniej spowodowane tym, że zablokowałem przyciąganie gracza do platformy, jako iż gracz wtedy nie mógł się poruszać, musiało to wpłynąć na ten bug.

**Comment by ciupagacz** [comment]
O ile tymczasowe rozwiązanie to na dzisiejszą wersję wypada idealnie :-)
