### ISSUE TITLE
A 1.0: Nie zamykający się poradnik

### ISSUE THREAD

**Issue by Ucheesename** [CiupagaPL/TEBowy_Dzien#4]
![Zrzut ekranu 2024-11-25 215356](https://github.com/user-attachments/assets/0b7842cb-38dd-492a-8b1d-9cb0c82bd91a)
![Zrzut ekranu 2024-11-25 215314](https://github.com/user-attachments/assets/2df6d29a-40f3-4616-a681-9f5953533a09)

Nie wiem czy to błąd ale można nie wyłączyć poradnika i sobie chodzić dopóki nie kliknie się esc. Gdy się spauzuje i kliknie się "Powtórz" to poradnik pojawia się tylko na chwilę po czym znika. Tak dzieje się z każdym poradnikiem na początku gry nie ważne czy wyjdzie się do lobby lub zmieni się poziom. Po przejściu bossa poradniki zaczynają działać normalnie ale po jakiejkolwiek śmierci błąd wraca.

**Comment by ciupagacz** [comment]
Escape nie wyłączał tutorialu przez co się on wracał za każdą pauzą. Ten sam problem jest z opisem nauczycieli lecz nie będę tworzył kolejnej notki <3

**Comment by ciupagacz** [comment]
Zostało naprawione przy przepisywaniu przejść :-D
