### ISSUE TITLE
A 1.0: Nie resetujące się ataki

### ISSUE THREAD

**Issue by Ucheesename** [CiupagaPL/TEBowy_Dzien#5]
![Zrzut ekranu 2024-11-25 231954](https://github.com/user-attachments/assets/a51933b7-8bc5-4411-a46e-3c439f292f2d)

Po śmierci przechodziłem poziom od nowa i kiedy dotarłem do bossa, cosie które latały kiedy umarłem nadal tam latały. od razu jak wejdzie się do bossa jeszcze przed opisem nauczyciela stare przeszkody potrafią zabić (jeśli jest się na hita) co raz mi zrobiły :'(.

**Comment by ciupagacz** [comment]
Również naprawione przy zmianie przejść
