### ISSUE TITLE
A 1.0: Błąd z animacją chmurki w trakcie ruchu

### ISSUE THREAD

**Issue by Ucheesename** [CiupagaPL/TEBowy_Dzien#6]
Trudno to uchwycić na screenie ale po pokonaniu bossa przez ok. sekundę chmurka zatrzymuje się w miejscu kiedy postacią można nadal sterować jak na chmurce i wygląda jakby latała.

**Comment by ciupagacz** [comment]
Podobnie zbugowania jest animacja chmurki, ścisle połączona z #8. Zajmę się w tym po przepracowaniu przejść.

**Comment by ciupagacz** [comment]
Nadal animacja nie jest dokończona lecz zostanie ona w następnej wersji, tak wszystko git
