### ISSUE TITLE
A 1.0: Złe skalowanie html

### ISSUE THREAD

**Issue by CiupagaPL** [CiupagaPL/TEBowy_Dzien#9]
Przy przeglądaniu starego kodu okazało się, że ustawiając ramkę część wartości nie jest skalowana. Przez to na każdej rozdzielczości ramka jest inaczej ustawiona.

**Comment by ciupagacz** [comment]
Naprawione w nowym patchu :- )
Z jakiegoś powdu cały skrypt menu.js połączył się z level.js i musiałem go przez pół godziny naprawiać <3
